<?php

return [
    'categories' => [
        'opening' => [
            'name' => 'Opening',
            'max_points' => 14,
        ],
        'probing' => [
            'name' => 'Probing',
            'max_points' => 19,
        ],
        'qualification' => [
            'name' => 'Qualification',
            'max_points' => 37,
        ],
        'closing' => [
            'name' => 'Closing',
            'max_points' => 11,
        ],
        'compliance' => [
            'name' => 'Compliance',
            'max_points' => 26,
        ],
    ],

    'criteria' => [
        // Opening (1.x)
        '1.1' => [
            'category' => 'opening',
            'name' => 'Used approved greeting',
            'severity' => 'minor',
            'points' => 2,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['hello flyland', 'flyland this is', 'this is flyland'],
            'fail_phrases' => ['hi there', 'flyland help line', 'flyland hotline'],
        ],
        '1.2' => [
            'category' => 'opening',
            'name' => 'Confirmed caller name and relationship',
            'severity' => 'minor',
            'points' => 2,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ["what's your name", 'can i get your name', 'may i have your name', 'name please'],
            'fail_phrases' => [],
        ],
        '1.3' => [
            'category' => 'opening',
            'name' => 'Identified reason for call promptly',
            'severity' => 'major',
            'points' => 5,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['how can i help', 'what brings you', 'reason for your call', 'what can i help you with'],
            'fail_phrases' => ['assumed reason', 'jumped to questions'],
        ],
        '1.4' => [
            'category' => 'opening',
            'name' => 'Verified caller location (state)',
            'severity' => 'major',
            'points' => 5,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['what state', 'which state', 'located in', 'state are you', 'what part of'],
            'fail_phrases' => ['never asks state'],
        ],

        // Probing (2.x)
        '2.1' => [
            'category' => 'probing',
            'name' => 'Asked about sober/clean time',
            'severity' => 'major',
            'points' => 5,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['last drink', 'last drug use', 'when was your last', 'how long has it been', 'clean time', 'sobriety'],
            'fail_phrases' => ['how long sober', 'skips time'],
        ],
        '2.2' => [
            'category' => 'probing',
            'name' => 'Inquired about substance/type of struggle',
            'severity' => 'major',
            'points' => 5,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['what substance', 'struggling with', 'alcohol drugs', 'drug or alcohol', 'what are you using'],
            'fail_phrases' => ['gives detox advice'],
        ],
        '2.3' => [
            'category' => 'probing',
            'name' => 'Asked about insurance type and details',
            'severity' => 'major',
            'points' => 5,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['type of insurance', 'private or state', 'medicaid', 'medicare', 'insurance do you have', 'what insurance'],
            'fail_phrases' => ['only asks do you have insurance', 'skips insurance'],
        ],
        '2.4' => [
            'category' => 'probing',
            'name' => 'Gathered additional info concisely',
            'severity' => 'minor',
            'points' => 2,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['openness to help', 'facility name', 'follow-up', 'willing to go'],
            'fail_phrases' => ['probes too many times', 'repeated questions'],
        ],
        '2.5' => [
            'category' => 'probing',
            'name' => 'Verified caller phone number',
            'severity' => 'minor',
            'points' => 2,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['best number', 'phone number', 'reach you', 'can i call you'],
            'fail_phrases' => ['skips phone when needed'],
        ],

        // Qualification (3.x)
        '3.1' => [
            'category' => 'qualification',
            'name' => 'Correctly assessed eligibility',
            'severity' => 'major',
            'points' => 5,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['transferring you', 'referring to', 'qualified', 'eligible'],
            'fail_phrases' => ['wrong transfer', 'wrong referral', 'offers self-pay when prohibited'],
        ],
        '3.2' => [
            'category' => 'qualification',
            'name' => 'Handled caller-specific needs correctly',
            'severity' => 'major',
            'points' => 5,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['treatment', 'samhsa', 'al-anon', 'aa', 'na', 'family support'],
            'fail_phrases' => ['wrong resource', 'incorrect referral'],
        ],
        '3.3' => [
            'category' => 'qualification',
            'name' => 'Used approved rebuttals/scripts',
            'severity' => 'major',
            'points' => 5,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['we are a helpline', 'to best help you', 'approved rebuttal', 'our purpose'],
            'fail_phrases' => ['deviates script', 'pressures caller'],
        ],
        '3.4' => [
            'category' => 'qualification',
            'name' => 'Avoided unqualified transfers',
            'severity' => 'ztp',
            'points' => 10,
            'ztp' => true,
            'na' => false,
            'pass_phrases' => ['does not transfer state insurance', 'no transfer for self-pay', 'correctly disqualified', 'not eligible'],
            'fail_phrases' => ['transfers state insurance', 'transfers self-pay', 'unqualified transfer'],
        ],
        '3.5' => [
            'category' => 'qualification',
            'name' => 'Escalated qualified leads promptly',
            'severity' => 'major',
            'points' => 5,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['transferring now', 'let me get you', 'transfer in', 'connecting you'],
            'fail_phrases' => ['delays transfer', 'fails to tag'],
        ],
        '3.6' => [
            'category' => 'qualification',
            'name' => 'Provided correct referrals for non-qualifying',
            'severity' => 'major',
            'points' => 5,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['988', 'samhsa', 'here are resources', 'national hotline'],
            'fail_phrases' => ['wrong referral', 'missing referral'],
        ],
        '3.7' => [
            'category' => 'qualification',
            'name' => 'Maintained empathy and professionalism',
            'severity' => 'minor',
            'points' => 2,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['i understand', 'thank you for', 'that\'s understandable', 'appreciate you', 'sorry to hear'],
            'fail_phrases' => ['irritation', 'no empathy', 'dismissive', 'rude'],
        ],

        // Closing (4.x)
        '4.1' => [
            'category' => 'closing',
            'name' => 'Ended call professionally',
            'severity' => 'minor',
            'points' => 2,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['thank you for calling', 'transferring now', 'here are the resources', 'anything else'],
            'fail_phrases' => ['abrupt hang-up', 'unclear next steps'],
        ],
        '4.2' => [
            'category' => 'closing',
            'name' => 'Documented in Salesforce within 5 minutes',
            'severity' => 'minor',
            'points' => 2,
            'ztp' => false,
            'na' => true,
            'pass_phrases' => [],
            'fail_phrases' => [],
        ],
        '4.3' => [
            'category' => 'closing',
            'name' => 'Applied correct star rating/disposition',
            'severity' => 'minor',
            'points' => 2,
            'ztp' => false,
            'na' => true,
            'pass_phrases' => [],
            'fail_phrases' => [],
        ],
        '4.4' => [
            'category' => 'closing',
            'name' => 'Noted follow-up/callback requests',
            'severity' => 'minor',
            'points' => 2,
            'ztp' => false,
            'na' => true,
            'pass_phrases' => [],
            'fail_phrases' => [],
        ],

        // Compliance (5.x)
        '5.1' => [
            'category' => 'compliance',
            'name' => 'Upheld patient confidentiality (HIPAA)',
            'severity' => 'ztp',
            'points' => 10,
            'ztp' => true,
            'na' => false,
            'pass_phrases' => ['hipaa', 'confidential', 'protected health', 'privacy'],
            'fail_phrases' => ['shares info unauthorized', 'hipaa breach', 'unauthorized disclosure'],
        ],
        '5.2' => [
            'category' => 'compliance',
            'name' => 'Avoided providing medical advice',
            'severity' => 'ztp',
            'points' => 10,
            'ztp' => true,
            'na' => false,
            'pass_phrases' => ['i cannot advise', 'not a medical', 'consult a professional', 'not a doctor'],
            'fail_phrases' => ['detox advice', 'withdrawal advice', 'dosage', 'treatment recommendation'],
        ],
        '5.3' => [
            'category' => 'compliance',
            'name' => 'Maintained response time',
            'severity' => 'minor',
            'points' => 2,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['responding promptly', 'answered quickly', 'right away'],
            'fail_phrases' => ['delayed response', 'slow to respond'],
        ],
        '5.4' => [
            'category' => 'compliance',
            'name' => 'Demonstrated soft skills',
            'severity' => 'minor',
            'points' => 2,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['active listening', 'clear communication', 'professional', 'patient'],
            'fail_phrases' => ['interruptions', 'unclear', 'rude'],
        ],
        '5.5' => [
            'category' => 'compliance',
            'name' => 'Adhered to SOP/tools',
            'severity' => 'major',
            'points' => 5,
            'ztp' => false,
            'na' => false,
            'pass_phrases' => ['using ctm', 'using zoho', 'approved tools', 'following procedure'],
            'fail_phrases' => ['unapproved script', 'deviates from tools'],
        ],
    ],

    'ztp_criteria' => ['3.4', '5.1', '5.2'],

    'always_na_criteria' => ['4.2', '4.3', '4.4'],

    'score_thresholds' => [
        'excellent' => ['min' => 85, 'max' => 100],
        'good' => ['min' => 70, 'max' => 84],
        'needs_improvement' => ['min' => 50, 'max' => 69],
        'poor' => ['min' => 0, 'max' => 49],
    ],

    'dispositions' => [
        'qualified_lead' => ['min_score' => 80, 'stars' => 4, 'action' => 'Transfer to treatment facility'],
        'warm_lead' => ['min_score' => 60, 'stars' => 3, 'action' => 'Provide resources and schedule callback'],
        'refer' => ['min_score' => 40, 'stars' => 2, 'action' => 'Provide SAMHSA/988 and general resources'],
        'do_not_refer' => ['min_score' => 0, 'stars' => 1, 'action' => 'Outside scope or not interested'],
    ],
];
